kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-clusterrole
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - default-psp